const tabList = [
  {
    title: "发现音乐",
    id: 1,
    show: true,
    children: [
      { title: "推荐", id: 11 },
      { title: "排行榜", id: 12 },
      { title: "歌单", id: 13 },
      { title: "主播电台", id: 14 },
      { title: "歌手", id: 15 },
      { title: "新碟上架", id: 16 },
    ],
  },
  {
    title: "我的音乐",
    id: 2,
    show: false,
    children: [
      { title: "流行", id: 11 },
      { title: "二次元", id: 12 },
      { title: "古風", id: 13 },
      { title: "古典樂", id: 14 },
      { title: "经典老歌", id: 15 },
      { title: "dj", id: 16 },
    ],
  },
  {
    title: "关注",
    id: 3,
    show: false,
    children: [
      { title: "羽泉组合", id: 11 },
      { title: "吴莫愁", id: 12 },
      { title: "林俊杰", id: 13 },
      { title: "akb48", id: 14 },
      { title: "乃木坂46", id: 15 },
      { title: "周杰伦", id: 16 },
    ],
  },
  {
    title: "商城",
    id: 4,
    show: false,
    children: [
      { title: "歌手周边", id: 11 },
      { title: "手办", id: 12 },
      { title: "专辑", id: 13 },
      { title: "光碟", id: 14 },
      { title: "歌手同款", id: 15 },
      { title: "歌手推荐", id: 16 },
    ],
  },
  {
    title: "音乐人",
    id: 5,
    show: false,
    children: [
      { title: "王磊", id: 11 },
      { title: "大张伟", id: 12 },
      { title: "陶喆", id: 13 },
      { title: "薛之谦", id: 14 },
      { title: "陈奕迅", id: 15 },
      { title: "毛不易", id: 16 },
    ],
  },
  {
    title: "云推歌",
    id: 6,
    show: false,
    children: [
      { title: "消愁", id: 11 },
      { title: "Music of cats", id: 12 },
      { title: "像我这样的人", id: 13 },
      { title: "她说", id: 14 },
      { title: "江南", id: 15 },
      { title: "美人鱼", id: 16 },
    ],
  },
  {
    title: "下载客户端",
    id: 7,
    children: [
      { title: "ios端", id: 11 },
      { title: "Android端", id: 12 },
      { title: "windows", id: 13 },
    ],
  },
];
